# brownie-config.yaml is special file with informaction for brownie like where you are going to build, deploy, grab things

dependencies:
 # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc: 
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

# dotenv is module which can load .env when you run a scipt
dotenv: .env
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False

# if you surround string with $ and {} it automaticlly be transform into environment variable 
wallets:
  from_key: ${PRIVATE_KEY}